endpoint
Shukura2/ridemyway-backend pull request #1
Opened 2021-06-22 14:21 UTC by Shukura2

2021-06-23 01:01 UTC, nosisky commented on src/controllers/RideHistory.js
> +    console.log(req.user)
You should not push code with console.log online.

2021-06-23 01:02 UTC, nosisky commented on src/controllers/RideHistory.js
> +  const {id} = req.user.user
Why repeat `user in the user object, you need to give it a better naming.

2021-06-23 01:02 UTC, nosisky commented on src/controllers/RideHistory.js
> +    console.log(req.body);
Take away the console.log, it should not be pushed online.

2021-06-23 01:03 UTC, nosisky commented on src/controllers/RideHistory.js
> +        driver_id, user_id, amount, destination
Your req body should not take snake_case as payload, it should take camelCase. e.g driverId and not driver_id.

2021-06-23 01:03 UTC, nosisky commented on src/controllers/home.js
> +export const indexPage = (req, res) => res.status(200).json({ message: testEnvironmentVariable });
This is no longer needed, you can take it ou.

2021-06-23 01:05 UTC, nosisky commented on src/controllers/messages.js
> +    const token = jwt.sign({
create a helper function to store the logic for jwt and reuse it where necessary.

2021-06-23 01:05 UTC, nosisky commented on src/controllers/offers.js
> +export const offersReq = async (req, res) => {
You should not abbreviate your function name, it needs to be descriptive as much as possible.

2021-06-23 01:07 UTC, nosisky commented on src/controllers/userController.js
> +    const token = jwt.sign({
Put this jwt signing logic into a helper function and re-use it in your code.

2021-06-23 01:07 UTC, nosisky commented on src/controllers/userController.js
> +  // const values = `'${email}', '${password}'`;
If this comments are no longer necessary, you can take them out.

2021-06-23 01:08 UTC, nosisky commented on src/controllers/userController.js
> +    const token = jwt.sign({
Dont forget to take this jwt logic into a helper function and reuse accorss board.

2021-06-23 01:10 UTC, nosisky commented on src/middleware/middleware.js
> +export const modifyMessage = (req, res, next) => {
Take away this since its no longer needed.

2021-06-23 01:11 UTC, nosisky commented on src/models/model.js
> +  if(datas){
data is already the plural format, it should remain data and not datas.

2021-06-23 01:12 UTC, nosisky commented on src/routes/index.js
> +indexRouter.get('/', usersPage);
It's a good practice to split this route into different files, user routes should be in a separate file, drivers route separate etc

2021-06-23 01:12 UTC, nosisky commented on src/settings.js
> +export const testEnvironmentVariable = process.env.TEST_ENV_VARIABLE;
This is no longer needed, you can take it out.

2021-06-23 01:14 UTC, nosisky commented on src/middleware/AuthMiddleware.js
> +    const emailExists = await driversModel.select('*', `WHERE "email" = '${email}'`);
Why select '*' when you only need the email?

2021-06-24 13:58 UTC, Shukura2 commented on src/middleware/middleware.js
> +export const modifyMessage = (req, res, next) => {
Do you mean the file?

2021-06-24 15:17 UTC, nosisky commented on src/middleware/middleware.js
> +export const modifyMessage = (req, res, next) => {
Yes, we don't need that anymore, it's from the tutorial right?

2021-06-29 07:24 UTC, nosisky requested changes

2021-06-29 07:24 UTC, nosisky commented on src/controllers/userController.js
> +    const token = jwt.sign({
This JWT logic should be in a helper function.

2021-06-29 14:52 UTC, nosisky commented on src/controllers/offers.js
> +    res.status(200).json({ offers: err.stack });
This is an error, it should not be offers, you are to return a message or error property here.

2021-06-29 14:53 UTC, nosisky commented on src/controllers/offers.js
> +    res.status(200).json({ offers: err.stack });
Fix this also, check through your code and fix this feedback, you can't return offers in a catch block, whatever got into the catch block is usually an error.

2021-06-29 14:53 UTC, nosisky commented on src/controllers/userController.js
> +    res.status(200).json({ users: err.stack });
Same issue here.

2021-06-29 14:54 UTC, nosisky commented on src/controllers/userController.js
> +    res.status(500).json({ update: err.stack });
Fix this, it should be error.

2021-06-29 14:55 UTC, nosisky commented on src/middleware/AuthMiddleware.js
> +    return error.message;
If this is a middleware, you are supposed to respond to the client with the message, res.send

2021-06-29 14:55 UTC, nosisky commented on src/middleware/AuthMiddleware.js
> +    return error.message;
res.send this error not return since this is a middleware.

2021-06-30 17:23 UTC, nosisky commented on src/controllers/RideHistory.js
> +    res.status(200).json({ error: data.rows });
Why returning error for a valid data?

2021-06-30 17:57 UTC, nosisky commented on src/controllers/driver.js
> +    res.status(200).json({ error: data.rows });
This is a status response, the key shouldn’t be error, please test all your endpoints on postman to be sure you’re returning the right data.

2021-06-30 17:57 UTC, nosisky commented on src/controllers/userController.js
> +    res.status(200).json({ error: data.rows });
Same issue here

2021-06-30 18:00 UTC, nosisky commented on src/helperFuncitonFile.js
> + * Helper function
Edit this comment, helper function to do what?

2021-07-01 14:23 UTC, nosisky commented on src/controllers/RideHistory.js
> +    res.status(200).json(data.rows[0]);
Have a data attribute here, dont send the entire object without the data attribute. {data: data.rows[0]}

2021-07-01 14:24 UTC, nosisky commented on src/controllers/offers.js
> +    res.status(200).json(data.rows[0]);
Same here, please fix `{data: data.rows[0]}`

2021-07-01 14:25 UTC, nosisky commented on src/controllers/userController.js
> +    res.status(200).json({ user: err.stack });
This is an error field, you are not sending a user here. It should either be a message or `error`

2021-07-01 14:25 UTC, nosisky commented on src/settings.js
> +export const testEnvironmentVariable = process.env.TEST_ENV_VARIABLE;
Take it out.

2021-07-01 16:21 UTC, nosisky requested changes

2021-07-01 16:21 UTC, nosisky commented on src/routes/driverRoute.js
> +driverRouter.put('/drivers/edit/:id', isLoggedIn, editDriver);
Route is already a PUT method, this should be: /driver/edit-profile you can get the driver id from the isLoggedIn as discussed initially.

2021-07-01 16:21 UTC, nosisky commented on src/routes/driverRoute.js
> +driverRouter.post('/drivers/login', checkDriverDetails, driverLogin);
Should be /driver/login.

2021-07-01 16:21 UTC, nosisky commented on src/routes/userRoute.js
> +userRouter.put('/users/edit/:id', isLoggedIn, editUser);
Route is already a PUT method, this should be: /user/edit-profile you can get the user id from the isLoggedIn middleware as discussed initially.

2021-07-01 16:21 UTC, nosisky commented on src/routes/offersRoute.js
> +offersRouter.delete('/offer/delete/:id', isLoggedIn, deleteOffer);
This route is already a `delete` route, there is no need to add delete to the route again.
This should be `/offer/:id`

2021-07-01 16:21 UTC, nosisky commented on src/routes/offersRoute.js
> +offersRouter.put('/offer/update/:id', isLoggedIn, updateOffer);
This route is already a PUT route, there is no need to add update to the route again.
This should be /offer/:id since PUT means UPDATE

2021-07-02 10:24 UTC, nosisky commented on src/routes/offersRoute.js
> +offersRouter.put('/offer/update/:id', isLoggedIn, updateOffer);
@Shukura2 This is the comment you missed.

2021-07-03 03:50 UTC, johnkingzy requested changes
Overall, impressive stuff you got here. Can you add more unit/integration testing?

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +    email: Joi.string().max(50).required(),
Why are you preventing users with email address of more than 50 characters? Personally I don't think this validation is necessary considering the standard maximum length of an email is 256 characters. You can read more here - https://www.lifewire.com/is-email-address-length-limited-1171110

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +    email: Joi.string().max(50).required(),
Instead I will recommend validating that the email address is valid with the correct format i.e `[username]@[domain]` - this is very important and will corrupt your data if not implemented i.e I can have a wrong format `12345-4744275947` as my email address.

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/RideHistory.js
> +    res.status(200).json({ data: data.rows[0] });
I think it'll be ideal to use `201` instead of `200` here, you can read more about http status code here - https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/RideHistory.js
> +  const driverId = req.user.data.id;
Why do you prefer having two nested objects? Don't you think it'll be more concise to just have `req.user.id` instead?

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/driver.js
> +    return res.status(200).json({
As mentioned above, `201` would be ideal when a new resource is created/added

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +  req.body.password = await bcrypt.hash(password, 10);
Nitpick: It best if we move this line to Line 40, reason is because if the email address already exists then there is no essence of doing this OR in other words, we want to hash the password when we are sure the email address is valid  so we don't execute this line if when we won't end up using the password

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +    email: Joi.string().max(50).required(),
Same comment as above, why the restriction of using email with more than 50 chars?

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +        message: 'Invalid Email',
I think we should adjust the http status code and the message to be more explicit; here's what I will recommend
- `409` means Conflict i.e similar data already exists
- message: 'Driver with the email address already exists' 

P.S Also don't forget to add the email validation here as well to make sure the email format is correct.

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +    if (!passwordValid) return res.status(400).send({ message: 'invalid password' });
Nitpick: format message - `Invalid password` or `Incorrect password` or `Password incorrect`

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +      message: 'Password is invalid',
Also always ensure your error messages are uniform when necessary.

2021-07-03 03:50 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> + * @param {Object} next - middleware
Is `next` a middleware or a `callback` function?

Keynotes
- `next` is the function *parameter* which is a callback.
- but the *argument* that will be passed to it in this context will act as a middleware

 :)

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/driver.js
> +        message: 'Invalid Email',
The message can be more explicit `Account with email address does not exists` OR `Incorrect Email address`

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/driver.js
> +      message: 'Driver login successfully!',
Nitpick: `Driver logged in successfully`

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/driver.js
> + * @returns {object} name edited
Nitpick: looks like your function is returning a response object

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/offers.js
> +    res.status(200).json({ data: data.rows[0] });
Also `201` would be ideal

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/userController.js
> +  const values = `'${fullName}', '${email}', '${password}'`;
We can validate the email format at this point also.

2021-07-03 03:50 UTC, johnkingzy commented on src/controllers/userController.js
> +    return res.status(200).json({
`201` would be ideal

2021-07-03 03:50 UTC, johnkingzy commented on src/utils/queries.js
> +    "fullName" varchar NOT NULL,
Looks like you are missing the size/lenght value in the `varchar` declaration, i.e `varchar(LENGTH)`

2021-07-03 03:50 UTC, johnkingzy commented on src/utils/queries.js
> +  email varchar(70) UNIQUE NOT NULL,
Is this length necessary? see previous comment

2021-07-13 11:05 UTC, johnkingzy commented on src/controllers/RideHistory.js
> +      results.rows
Please make sure all your endpoint response have the same format

2021-07-13 12:12 UTC, johnkingzy commented on src/controllers/driver.js
> +      token,
same here, make sure your endpoint response have the same format

2021-07-13 12:13 UTC, johnkingzy commented on src/controllers/userController.js
> +      token,
Make sure your endpoint have the same format, you might want move `user` and `token` inside a `data` object

2021-07-13 12:16 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +    return res.status(400).send({
If the email already exists, shouldn't that be a conflict - 409?

2021-07-13 12:16 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +    res.status(400).send({
Same here - 409

2021-07-13 12:19 UTC, johnkingzy requested changes
Looks good so far, I have some feedback

2021-07-13 13:52 UTC, Shukura2 commented on src/controllers/userController.js
> +      token,
Can you make this feedback more clear

2021-07-23 11:24 UTC, johnkingzy approved these changes
All good 👍

2021-07-23 11:26 UTC, merged